add tabTracker, add JSDoc, organize and format the code
Dylan700/LeastRecentlyUsedTabsExtension pull request #17
Opened 2024-10-14 02:55 UTC by Megaemce

Fix the issue (#13). 
Please test on your site.

2024-10-14 03:57 UTC, Dylan700 commented
Thanks heaps, I'll have a look and test over the next few days and update you if there are any changes!

2024-10-19 07:32 UTC, Dylan700 commented
Ok, so just had a look, everything works well, very slightly slower performance-wise but oh well. Just have a few comments for you to address before we merge this!

2024-10-19 07:35 UTC, Dylan700 requested changes

2024-10-19 07:35 UTC, Dylan700 commented on CHANGELOG.md
Can you please remove this file? If you would like to include this then it would be better in another PR.

2024-10-19 07:35 UTC, Dylan700 commented on package-lock.json
Please set the version back to 1.1.1, the CI I have created will automatically update this for us.

2024-10-19 07:35 UTC, Dylan700 commented on package.json
Please set the version back to 1.1.1, the CI I have created will automatically update this for us.

2024-10-19 07:35 UTC, Dylan700 commented on src/tabTracker.ts
Looks good

2024-10-19 13:03 UTC, Megaemce commented on CHANGELOG.md
this file was already in your repo, I just updated it. It's used by marketplace to show the diffs.

2024-10-19 13:12 UTC, Megaemce commented
Fixed, The slow performance is pretty suprising, as the only difference is just the object contained in the memory that should takes around few kb of memory...

2024-10-19 23:36 UTC, Dylan700 requested changes
Thanks so much, appreciate your contributions here. Once you add that file back in I'll merge and release.

2024-10-19 23:36 UTC, Dylan700 commented on CHANGELOG.md
Sorry to mess you around, you are right, can you please add this file back in? You can copy it from the previous commit. I forgot that this is needed since I haven't kept it up to date... 👀 oops

2024-10-21 01:47 UTC, Dylan700 approved these changes
Looks good

2024-10-21 01:48 UTC, merged